# Generated by Django 4.2.23 on 2025-06-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=20)),
                ('is_holiday', models.BooleanField()),
                ('time_period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('launch_date', models.DateField()),
                ('performance_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('market_size', models.CharField(max_length=20)),
                ('average_income', models.FloatField()),
                ('market_potential', models.FloatField()),
                ('growth_opportunity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('store_type', models.CharField(max_length=50)),
                ('store_size', models.CharField(max_length=20)),
                ('store_location', models.CharField(max_length=50)),
                ('store_performance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FactSalesTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('time_period', models.CharField(max_length=20)),
                ('sales_amount', models.FloatField()),
                ('units_sold', models.IntegerField()),
                ('profit_margin', models.FloatField()),
                ('growth_rate', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.product')),
            ],
        ),
        migrations.CreateModel(
            name='FactSalesRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('sales_amount', models.FloatField()),
                ('units_sold', models.IntegerField()),
                ('operating_profit', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.region')),
            ],
        ),
        migrations.CreateModel(
            name='FactProductProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sales_amount', models.FloatField()),
                ('operating_profit', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('margin', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.product')),
            ],
        ),
    ]
