# Generated by Django 4.2.23 on 2025-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factproductprofit',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='factsalestrend',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
